# About Allison 

## Education 

* ___Columbia University Mailman School of Public Health (Expected May 2021)___
Master's of Public Health, Population & Family Health, Public Health Research Methods Certification 

* ___Washington University in St. Louis, St. Louis, MO (May 2018)___
Bachelor of Arts, Major in Anthropology, Minors in Spanish and Psychological & Brain Sciences

## Research 

* ___Society and Health Research Center, Universidad Mayor, Santiago, Chile (June 2020-Present)___ Conduct qualitative coding and analysis of in-depth interviews exploring injection drug use patterns among female injection drug users in Tijuana, Mexico

* ___National Center for Disaster Preparedness, Earth Institute, New York, NY (February 2020-Present)___
Conducted research in support of the Resilient Children Resilient Communities initiative to build child-focused disaster preparedness in communities affected by hurricanes Florence and Maria

* ___Washington University in St. Louis St. Louis, MO January–May 2018)___
Led a research team in conducting in-depth comparative research on the natural resource nexus in Urban Asia

* ___School for International Training Valparaíso, Chile and St. Louis, MO (May 2017 - May 2018)___
Conducted an independent research project on social recovery and resilience within communities affected by the Great Fire of Valparaíso, Chile of 2014; Utilized an ethnographic content analysis method to analyze data collected through semi-structured interviews, participant observation, and literature review

## Professional Experience 

* ___Community Impact at Columbia University, New York, NY (May – August 2019, May – August 2019)___
Facilitated non-profit development and administration: tracked donations and maintained contact with major donors, planned fundraising events and Community Impact’s autumn retreat, assisted director with administrative tasks; Maintained partnerships with community organizations in Upper Manhattan

* ___Primeros Pasos Quetzaltenango, Guatemala (September 2018-April 2019)___
Educated rural communities about hygiene, sanitation, diet, prenatal health and disease prevention; Monitored children and parents involved in nutritional recuperation program; Designed fundraising materials and prepared for upcoming fundraising events; Composed quarterly and annual reports

* ___Planned Parenthood of Nassau Country, Hempstead, NY (June-August 2017)___
Performed advocacy work and outreach: managed the supporter database, collected petition signatures, cold called constituents and potential donors, registered voters, and advocated on Capital Hill during the ACA repeal; Facilitated volunteer engagement and training sessions to build the volunteer platform; Contributed to the social media campaign “So Much More” to inform youth about Planned Parenthood’s services

* ___SUNY Downstate Medical Center, School of Public Health, New York, NY (June–August 2017)___
Volunteered with Dr. Monica Sweeney, clinical professor and vice dean for global engagement; Developed contacts with global health organizations to generate overseas opportunities for Downstate students

* ___Harvest Home Farmer’s Market, New York, NY (May–August 2016)___
Improved marketing strategies to increase visibilities of farmers’ markets and food security programs for low-income families; Managed social media accounts and composed daily posts; Catalogued activities of farmers’ market site coordinators and prepared NYC DoH “Health Bucks”

* ___City Faces, St. Louis, MO (August 2015-May 2018)___
Tutored students from low-income public housing in St. Louis; Maintained and developed support system for low-income children and families


